CREATE DATABASE Decryptoid;
CREATE TABLE Users(
	UserId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Username VARCHAR(255) NOT NULL UNIQUE,
	Email VARCHAR(255) NOT NULL UNIQUE,
	PasswordHash VARCHAR(255) NOT NULL
);
CREATE TABLE BlacklistedTokens (
	BlasklistedTokenId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Token VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE DecryptoidUses (
	DecryptoidUseId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	InputText TEXT NOT NULL,
	CipherUsed VARCHAR(500) NOT NULL,
	UsedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	UserId INT,
	FOREIGN KEY (UserId) REFERENCES Users(UserId)
);