CREATE DATABASE Decryptoid;
CREATE TABLE Users(
	UserId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Username VARCHAR(255) NOT NULL UNIQUE,
	PasswordHash VARCHAR(255) NOT NULL
);
CREATE TABLE BlacklistedTokens (
	BlasklistedTokenId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Token VARCHAR(255) NOT NULL UNIQUE
);